{
 "title": "Zenox V2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System Health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "discord_connected{shard=\"None\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "discord_connected{shard!=\"None\"}",
     "legendFormat": "{{job}} - Shard {{shard}}"
    }
   ]
  },
  {
   "title": "Discord Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "discord_latency{shard!=\"None\"}",
     "legendFormat": "{{job}} - Shard {{shard}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "discord_ram_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() - discord_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Members in all Guilds",
   "type": "timeseries",
   "description": "Combined amount of users in all guilds the bot is on",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "discord_guild_members", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Guilds over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "discord_guilds", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "CPU Activity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "discord_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Guild Locales",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "discord_guild_locale", "legendFormat": "__auto" }
   ]
  }
 ]
}